cmake_minimum_required(VERSION 3.27)
if(NOT PROBE)
    execute_process(COMMAND "${CMAKE_COMMAND}" -DPROBE=ON "-DCASE=${CASE}"
            "-DTEST_DIRECTORY=${TEST_DIRECTORY}" -P "${CMAKE_CURRENT_LIST_FILE}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(CASE MATCHES "^(reuse|boolean)$")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Cache reuse failed: ${output}\n${error}")
        endif()
    else()
        if(CASE STREQUAL "missing")
            set(expected "Dependency package is missing")
        elseif(CASE STREQUAL "multiconfig")
            set(expected "Prebuilt dependencies require a single-config generator")
        else()
            set(expected "Dependency ABI/recipe mismatch")
        endif()
        if(result EQUAL 0 OR NOT "${output}\n${error}" MATCHES "${expected}")
            message(FATAL_ERROR "Expected rejection for ${CASE}: ${output}\n${error}")
        endif()
    endif()
    return()
endif()

include("${CMAKE_CURRENT_LIST_DIR}/../../cmake/DependencyCache.cmake")
set(CMAKE_BUILD_TYPE Debug)
set(CMAKE_CXX_COMPILER_ID MSVC)
set(CMAKE_CXX_COMPILER_VERSION 19.50)
set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreadedDebugDLL)
set(METALLIC_ENABLE_OPENUSD OFF)
if(CASE STREQUAL "boolean")
    set(METALLIC_ENABLE_OPENUSD ON)
endif()
set(METALLIC_DEPENDENCY_ROOT "${TEST_DIRECTORY}/${CASE}")
metallic_dependency_identity()
set(original_hash "${METALLIC_DEPENDENCY_HASH}")
file(MAKE_DIRECTORY "${METALLIC_DEPENDENCY_ROOT}")
if(NOT CASE STREQUAL "missing")
    file(WRITE "${METALLIC_DEPENDENCY_ROOT}/metallic-dependencies.txt"
        "${METALLIC_DEPENDENCY_IDENTITY}")
endif()

if(CASE STREQUAL "boolean")
    set(METALLIC_ENABLE_OPENUSD TRUE)
elseif(CASE STREQUAL "compiler")
    set(CMAKE_CXX_COMPILER_VERSION 19.51)
elseif(CASE STREQUAL "configuration")
    set(CMAKE_BUILD_TYPE Release)
elseif(CASE STREQUAL "crt")
    set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreadedDebug)
elseif(CASE STREQUAL "flags")
    set(CMAKE_CXX_FLAGS /DANOTHER_ABI)
elseif(CASE STREQUAL "features")
    set(METALLIC_ENABLE_OPENUSD ON)
elseif(CASE STREQUAL "multiconfig")
    set(CMAKE_CONFIGURATION_TYPES Debug Release)
endif()
metallic_dependency_identity()
if(CASE MATCHES "^(reuse|boolean)$")
    if(NOT original_hash STREQUAL METALLIC_DEPENDENCY_HASH)
        message(FATAL_ERROR "Identical dependency inputs did not produce an identical key")
    endif()
elseif(NOT CASE STREQUAL "missing" AND original_hash STREQUAL METALLIC_DEPENDENCY_HASH)
    message(FATAL_ERROR "Changed ${CASE} was not included in the dependency key")
endif()
metallic_check_dependency_package()
