cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED SOURCE_DIRECTORY OR NOT DEFINED TEST_DIRECTORY)
    message(FATAL_ERROR "SOURCE_DIRECTORY and TEST_DIRECTORY are required")
endif()

function(run_fixture_build root expected)
    file(WRITE "${root}/expected.txt" "${expected}")
    execute_process(COMMAND "${CMAKE_COMMAND}" --build "${root}/build" --config Release
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Fixture build failed:\n${output}\n${errors}")
    endif()
    file(READ "${root}/build/deployed-path-Release.txt" deployed)
    if(expected)
        if(NOT EXISTS "${deployed}")
            message(FATAL_ERROR "Enabled NR runtime was not deployed")
        endif()
        file(READ "${deployed}" contents)
        if(NOT contents STREQUAL "Local NR test fixture")
            message(FATAL_ERROR "A runtime outside External was deployed")
        endif()
    elseif(EXISTS "${deployed}")
        message(FATAL_ERROR "Disabled build retained a stale NR runtime")
    endif()
endfunction()

foreach(case IN ITEMS missing missing_enabled enabled disabled external_override
        external_override_local directory no_streamline missing_headers lfs_headers unsupported)
    set(root "${TEST_DIRECTORY}/${case}")
    set(headers "${root}/sdk/external/ngx-sdk/include")
    file(MAKE_DIRECTORY "${root}/External" "${headers}")
    foreach(header IN ITEMS nvsdk_ngx_vk.h nvsdk_ngx_params.h)
        file(WRITE "${headers}/${header}" "// NGX test fixture\n")
    endforeach()
    set(expected 0)
    set(test_build OFF)
    set(enable_args -UMETALLIC_ENABLE_DLSS_NR)
    if(case STREQUAL "missing_enabled")
        set(enable_args -DMETALLIC_ENABLE_DLSS_NR=ON)
    elseif(case STREQUAL "disabled")
        set(enable_args -DMETALLIC_ENABLE_DLSS_NR=OFF)
    endif()
    if(case MATCHES "^(enabled|disabled|external_override_local|no_streamline|missing_headers|lfs_headers|unsupported)$")
        file(WRITE "${root}/External/nvngx_dlssnr.dll" "Local NR test fixture")
    elseif(case STREQUAL "directory")
        file(MAKE_DIRECTORY "${root}/External/nvngx_dlssnr.dll")
    endif()
    if(case STREQUAL "missing_headers")
        file(REMOVE "${headers}/nvsdk_ngx_vk.h")
    elseif(case STREQUAL "lfs_headers")
        file(WRITE "${headers}/nvsdk_ngx_vk.h" "version https://git-lfs.github.com/spec/v1\n")
    elseif(case MATCHES "^(enabled|external_override_local)$")
        set(expected 1)
    endif()
    if(case STREQUAL "enabled")
        set(test_build ON)
    endif()
    # The legacy override exists but must never substitute for the local DLL.
    file(WRITE "${root}/elsewhere.dll" "Outside NR test fixture")
    file(WRITE "${root}/expected.txt" "${expected}")
    file(WRITE "${root}/Main.cpp"
        "static_assert(METALLIC_HAS_DLSS_NR == EXPECT_NR);\nint main() { return 0; }\n")
    file(WRITE "${root}/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.20)
if(TEST_BUILD)
    project(DlssNrFixture CXX)
else()
    project(DlssNrFixture NONE)
endif()
set(WIN32 TRUE)
set(MSVC TRUE)
set(CMAKE_SIZEOF_VOID_P 8)
set(METALLIC_HAS_STREAMLINE 1)
set(METALLIC_STREAMLINE_SDK_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/sdk")
if(CASE STREQUAL "no_streamline")
    set(METALLIC_HAS_STREAMLINE 0)
elseif(CASE STREQUAL "unsupported")
    set(WIN32 FALSE)
endif()
include("${SOURCE_DIRECTORY}/cmake/SetupDlssNr.cmake")
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/expected.txt" expected)
if(NOT METALLIC_HAS_DLSS_NR EQUAL expected)
    message(FATAL_ERROR "Unexpected NR availability: ${METALLIC_HAS_DLSS_NR}, expected ${expected}")
endif()
get_target_property(definitions metallic_dlss_nr INTERFACE_COMPILE_DEFINITIONS)
if(NOT "METALLIC_HAS_DLSS_NR=${expected}" IN_LIST definitions)
    message(FATAL_ERROR "Consumers did not receive the NR compile definition")
endif()
if(NOT METALLIC_DLSS_NR_RUNTIME STREQUAL "${CMAKE_CURRENT_SOURCE_DIR}/External/nvngx_dlssnr.dll")
    message(FATAL_ERROR "Legacy runtime override bypassed the manual External installation")
endif()
if(TEST_BUILD)
    add_executable(Fixture Main.cpp)
    target_link_libraries(Fixture PRIVATE metallic::dlss_nr)
    target_compile_definitions(Fixture PRIVATE EXPECT_NR=${expected})
    metallic_copy_dlss_nr_runtime(Fixture)
    file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/deployed-path-$<CONFIG>.txt"
        CONTENT "$<TARGET_FILE_DIR:Fixture>/nvngx_dlssnr.dll")
endif()
]=])
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${root}" -B "${root}/build"
        -G "${TEST_GENERATOR}" "-DCMAKE_MAKE_PROGRAM=${TEST_MAKE_PROGRAM}"
        -DCMAKE_BUILD_TYPE=Release "-DSOURCE_DIRECTORY=${SOURCE_DIRECTORY}"
        "-DCASE=${case}" "-DTEST_BUILD=${test_build}" ${enable_args}
        "-DMETALLIC_DLSS_NR_RUNTIME=${root}/elsewhere.dll"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "${case} failed:\n${output}\n${errors}")
    endif()
    if(test_build)
        run_fixture_build("${root}" 1)
        # Ordinary builds must detect removal/addition, update the macro, and
        # remove/redeploy the DLL without an explicit configure command.
        file(REMOVE "${root}/External/nvngx_dlssnr.dll")
        run_fixture_build("${root}" 0)
        file(WRITE "${root}/External/nvngx_dlssnr.dll" "Local NR test fixture")
        run_fixture_build("${root}" 1)
    endif()
endforeach()
message(STATUS "DLSS-NR manual installation, availability, cache override and deployment cases passed")
