cmake_minimum_required(VERSION 3.20)

if(CHILD)
    set(CMAKE_SOURCE_DIR "${FIXTURE}")
    set(WIN32 TRUE)
    set(CMAKE_SIZEOF_VOID_P 8)
    set(CMAKE_SYSTEM_PROCESSOR AMD64)
    set(CMAKE_CROSSCOMPILING FALSE)
    if(CASE STREQUAL "existing")
        set(METALLIC_POWERSHELL_EXECUTABLE "must-not-run")
    elseif(CASE STREQUAL "custom")
        set(SLANG_ROOT "${FIXTURE}/custom SDK")
        set(METALLIC_POWERSHELL_EXECUTABLE "must-not-run")
    elseif(CASE STREQUAL "disabled")
        set(METALLIC_SLANG_AUTO_DOWNLOAD OFF CACHE BOOL "")
    elseif(CASE STREQUAL "unsupported")
        set(CMAKE_SYSTEM_PROCESSOR ARM64)
    endif()
    include("${SOURCE_DIRECTORY}/cmake/SetupSlang.cmake")
    if(CASE STREQUAL "custom" AND NOT METALLIC_SLANG_ROOT STREQUAL SLANG_ROOT)
        message(FATAL_ERROR "Explicit SDK root was ignored")
    endif()
    return()
endif()

string(RANDOM LENGTH 12 fixture_id)
set(FIXTURE "${TEST_DIRECTORY}/${CASE}-${fixture_id}")
file(MAKE_DIRECTORY "${FIXTURE}/scripts")
file(COPY "${SOURCE_DIRECTORY}/scripts/InstallSlang.ps1" DESTINATION "${FIXTURE}/scripts")
if(CASE STREQUAL "existing")
    file(MAKE_DIRECTORY "${FIXTURE}/External/slang/cmake")
    file(WRITE "${FIXTURE}/External/slang/cmake/slangConfig.cmake" "# Existing SDK\n")
elseif(CASE STREQUAL "partial")
    file(MAKE_DIRECTORY "${FIXTURE}/External/slang")
    file(WRITE "${FIXTURE}/External/slang/keep.txt" "preserve me")
elseif(CASE STREQUAL "cached")
    if(NOT EXISTS "${ARCHIVE}")
        message(FATAL_ERROR "Pass ARCHIVE to run the real cached SDK installation test")
    endif()
    file(MAKE_DIRECTORY "${FIXTURE}/.cache/slang")
    file(CREATE_LINK "${ARCHIVE}"
        "${FIXTURE}/.cache/slang/slang-2026.18.2-windows-x86_64.zip" COPY_ON_ERROR)
endif()

execute_process(COMMAND "${CMAKE_COMMAND}" -DCHILD=ON "-DCASE=${CASE}"
    "-DFIXTURE=${FIXTURE}" "-DSOURCE_DIRECTORY=${SOURCE_DIRECTORY}"
    -P "${CMAKE_CURRENT_LIST_FILE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(CASE MATCHES "^(disabled|unsupported|partial)$")
    if(result STREQUAL "0")
        message(FATAL_ERROR "Expected failure for ${CASE}")
    endif()
    if(CASE STREQUAL "disabled" AND NOT "${output}${error}" MATCHES "Enable METALLIC_SLANG_AUTO_DOWNLOAD")
        message(FATAL_ERROR "Missing offline setup hint: ${output}${error}")
    elseif(CASE STREQUAL "unsupported" AND NOT "${output}${error}" MATCHES "native Windows x64")
        message(FATAL_ERROR "Missing platform setup hint: ${output}${error}")
    elseif(CASE STREQUAL "partial")
        file(READ "${FIXTURE}/External/slang/keep.txt" preserved)
        if(NOT preserved STREQUAL "preserve me" OR NOT "${output}${error}" MATCHES "Destination already exists")
            message(FATAL_ERROR "Existing SDK not protected: ${output}${error}")
        endif()
    endif()
elseif(NOT result STREQUAL "0")
    message(FATAL_ERROR "${CASE} failed: ${output}${error}")
endif()
if(CASE STREQUAL "cached")
    # Run again with an unusable installer to prove the SDK is reused.
    execute_process(COMMAND "${CMAKE_COMMAND}" -DCHILD=ON -DCASE=existing
        "-DFIXTURE=${FIXTURE}" "-DSOURCE_DIRECTORY=${SOURCE_DIRECTORY}"
        -P "${CMAKE_CURRENT_LIST_FILE}" RESULT_VARIABLE reused)
    if(NOT reused STREQUAL "0")
        message(FATAL_ERROR "Installed SDK was not reused")
    endif()
endif()
message(STATUS "Slang bootstrap ${CASE}: passed")
