#language slang 2026
module GPUDriven;

__include "GPUDriven/ConservativeOcclusion.slang";
__include "GPUDriven/GPUDrivenCullingCommon.slang";
__include "GPUDriven/GPUDrivenRasterCommon.slang";
__include "GPUDriven/GPUDrivenSceneCommon.slang";
__include "GPUDriven/HybridClusterBins.slang";
__include "GPUDriven/HybridRasterCommon.slang";
__include "GPUDriven/HybridRasterTriangle.slang";
__include "GPUDriven/MaterialBinningCommon.slang";
__include "GPUDriven/MeshletLod.slang";
__include "GPUDriven/MeshletLodMetric.slang";
