#language slang 2026
module Lighting;
import WorkingColor;

__include "Lighting/ClusterLightGridCommon.slang";
__include "Lighting/EnvironmentPrefilter.slang";
__include "Lighting/PhotometricLighting.slang";
__include "Lighting/EnvironmentTransport.slang";
__include "Lighting/ProceduralEnvironment.slang";
__include "Lighting/PunctualLightSampling.slang";
__include "Lighting/FiniteCelestialSampling.slang";
__include "Lighting/ScreenSpaceShadowCommon.slang";
