/*
Copyright (c) 2022, NVIDIA CORPORATION. All rights reserved.

NVIDIA CORPORATION and its licensors retain all intellectual property
and proprietary rights in and to this software, related documentation
and any modifications thereto. Any use, reproduction, disclosure or
distribution of this software and related documentation without an express
license agreement from NVIDIA CORPORATION is strictly prohibited.
*/
// Metallic native descriptor handles. Generated by scripts/VendorNrd.py.
#include "SIGMA_SmoothTiles.resources.hlsli"
#define gWorldToView (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gWorldToView)
#define gViewToClip (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gViewToClip)
#define gWorldToClipPrev (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gWorldToClipPrev)
#define gWorldToViewPrev (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gWorldToViewPrev)
#define gRotator (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gRotator)
#define gRotatorPost (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gRotatorPost)
#define gViewVectorWorld (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gViewVectorWorld)
#define gLightDirectionView (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gLightDirectionView)
#define gFrustum (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gFrustum)
#define gFrustumPrev (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gFrustumPrev)
#define gCameraDelta (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gCameraDelta)
#define gMvScale (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gMvScale)
#define gResourceSizeInv (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gResourceSizeInv)
#define gResourceSizeInvPrev (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gResourceSizeInvPrev)
#define gRectSize (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gRectSize)
#define gRectSizeInv (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gRectSizeInv)
#define gRectSizePrev (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gRectSizePrev)
#define gResolutionScale (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gResolutionScale)
#define gRectOffset (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gRectOffset)
#define gPrintfAt (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gPrintfAt)
#define gRectOrigin (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gRectOrigin)
#define gRectSizeMinusOne (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gRectSizeMinusOne)
#define gTilesSizeMinusOne (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gTilesSizeMinusOne)
#define gOrthoMode (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gOrthoMode)
#define gUnproject (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gUnproject)
#define gDenoisingRange (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gDenoisingRange)
#define gPlaneDistSensitivity (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gPlaneDistSensitivity)
#define gStabilizationStrength (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gStabilizationStrength)
#define gDebug (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gDebug)
#define gSplitScreen (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gSplitScreen)
#define gViewZScale (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gViewZScale)
#define gMinRectDimMulUnproject (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gMinRectDimMulUnproject)
#define gFrameIndex (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gFrameIndex)
#define gIsRectChanged (((SIGMA_SmoothTilesConstants*)gNrdPush.constants)->nrd_gIsRectChanged)
#define gNearestClamp (*DescriptorHandle<SamplerState>(uint2(gNrdPush.resources->samplers[0], 0)))
#define gLinearClamp (*DescriptorHandle<SamplerState>(uint2(gNrdPush.resources->samplers[1], 0)))
#define gIn_Tiles (*DescriptorHandle<Texture2D<float3>>(uint2(gNrdPush.resources->sampled[0], 0)))
#define gOut_Tiles (*DescriptorHandle<RWTexture2D<float2>>(uint2(gNrdPush.resources->storage[0], 0)))
