string(TIMESTAMP stamp "%Y%m%dT%H%M%S")
string(RANDOM LENGTH 8 suffix)
set(root "${SOURCE}/.tmp/testbench-shrinker/${stamp}-${suffix}")
set(layer_arguments)
if(NOT "${LAYER_PATH}" STREQUAL "")
    list(APPEND layer_arguments --tb-layer-path "${LAYER_PATH}")
endif()
execute_process(COMMAND "${EXECUTABLE}" --tb-run --tb-suite sequence-fixtures --tb-validation sync
    --tb-require-all --output-dir "${root}/original" ${layer_arguments}
    WORKING_DIRECTORY "${SOURCE}" RESULT_VARIABLE code OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 45)
if(NOT code EQUAL 1)
    message(FATAL_ERROR "Expected oracle fault did not fail: ${code} ${stdout} ${stderr}")
endif()
set(original "${root}/original/core/RhiCommand.buffer_sequence_injected_oracle/0")
execute_process(COMMAND "${EXECUTABLE}" --tb-shrink "${original}" --output-dir "${root}/shrink"
    WORKING_DIRECTORY "${SOURCE}" RESULT_VARIABLE code OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 140)
if(NOT code EQUAL 0)
    message(FATAL_ERROR "Shrinker failed: ${stdout} ${stderr}")
endif()
file(READ "${root}/shrink/shrink.json" report)
string(JSON minimal GET "${report}" minimalCommands)
string(JSON proved GET "${report}" oneDeletionMinimal)
string(JSON confirms GET "${report}" confirmationsPerAcceptedProgram)
if(NOT minimal EQUAL 1 OR NOT proved OR NOT confirms EQUAL 2)
    message(FATAL_ERROR "Shrinker did not retain only the trigger: ${report}")
endif()
execute_process(COMMAND "${EXECUTABLE}" --tb-replay "${root}/shrink/minimal" --output-dir "${root}/replay"
    WORKING_DIRECTORY "${SOURCE}" RESULT_VARIABLE code OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 45)
file(READ "${root}/replay/results.json" replay)
string(JSON status GET "${replay}" cases 0 status)
file(READ "${root}/replay/core/RhiCommand.buffer_sequence_injected_oracle/0/sequence-diff.json" diff)
string(JSON signature GET "${diff}" signature)
string(JSON expected GET "${report}" signature)
if(NOT code EQUAL 1 OR NOT status STREQUAL "Fail" OR NOT signature STREQUAL expected)
    message(FATAL_ERROR "Minimized replay lost failure category: ${stdout} ${stderr}")
endif()
message(STATUS "Verified real GPU execution with injected CPU oracle fault, isolated shrinking and minimized replay: ${root}")
