# No WILL_FAIL shortcut: setup/crash/timeout must not satisfy this negative test.
string(TIMESTAMP run_id "%Y%m%dT%H%M%S")
string(RANDOM LENGTH 8 suffix)
set(root "${SOURCE}/.tmp/testbench-sync-probe/${run_id}-${suffix}")
set(layer_arguments)
if(NOT "${LAYER_PATH}" STREQUAL "")
    list(APPEND layer_arguments --tb-layer-path "${LAYER_PATH}")
endif()
foreach(mode IN ITEMS core sync)
    set(output "${root}/${mode}")
    execute_process(COMMAND "${EXECUTABLE}" --tb-run --tb-suite validation-probe
        --tb-validation "${mode}" --tb-require-all --output-dir "${output}" ${layer_arguments}
        WORKING_DIRECTORY "${SOURCE}" RESULT_VARIABLE code OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 45)
    file(READ "${output}/results.json" results)
    string(JSON count LENGTH "${results}" cases)
    string(JSON status GET "${results}" cases 0 status)
    string(JSON executed GET "${results}" cases 0 executed)
    set(sample "${output}/core/RhiValidation.sync_activation_probe/0")
    file(READ "${sample}/validation.json" validation)
    string(JSON capture_failed GET "${validation}" captureFailed)
    string(JSON messages LENGTH "${validation}" messages)
    file(READ "${sample}/capabilities.json" capabilities)
    string(JSON effective_mode GET "${capabilities}" validationMode)
    if(NOT count EQUAL 1 OR NOT executed OR capture_failed OR NOT effective_mode STREQUAL mode)
        message(FATAL_ERROR "Invalid activation probe evidence: ${stdout} ${stderr}")
    endif()
    if(mode STREQUAL "core")
        if(NOT code EQUAL 0 OR NOT status STREQUAL "Pass" OR NOT messages EQUAL 0)
            message(FATAL_ERROR "Core control did not pass cleanly: ${stdout} ${validation}")
        endif()
    else()
        if(NOT code EQUAL 1 OR NOT status STREQUAL "Fail" OR NOT messages EQUAL 1)
            message(FATAL_ERROR "Sync mode did not detect exactly one hazard: ${stdout} ${validation}")
        endif()
        string(JSON id GET "${validation}" messages 0 id)
        string(JSON phase GET "${validation}" messages 0 phase)
        if(NOT id STREQUAL "SYNC-HAZARD-WRITE-AFTER-WRITE" OR NOT phase STREQUAL "run")
            message(FATAL_ERROR "Unexpected validation failure: ${validation}")
        endif()
    endif()
endforeach()
message(STATUS "Verified real synchronization activation and fail-closed audit; evidence: ${root}")
