string(TIMESTAMP stamp "%Y%m%dT%H%M%S")
string(RANDOM LENGTH 8 suffix)
set(root "${SOURCE}/.tmp/testbench-trace/${stamp}-${suffix}")
set(layer_arguments)
if(NOT "${LAYER_PATH}" STREQUAL "")
    list(APPEND layer_arguments --tb-layer-path "${LAYER_PATH}")
endif()
foreach(mode IN ITEMS off on)
    set(trace_arguments)
    if(mode STREQUAL "on")
        list(APPEND trace_arguments --tb-trace)
    endif()
    foreach(suite IN ITEMS async property core)
        if(suite STREQUAL "async")
            set(filter "RhiRendering.frame_self_submit_two_slots*")
            set(profile async)
        elseif(suite STREQUAL "property")
            set(filter "RhiCommand.buffer_sequence")
            set(profile core)
        else()
            set(filter "RhiCommand.texture_odd_mips_layers_volume_readback")
            set(profile core)
        endif()
        set(output "${root}/${mode}/${suite}")
        execute_process(COMMAND "${EXECUTABLE}" --tb-run --tb-suite "${suite}" --tb-filter "${filter}"
            --tb-validation sync --tb-require-all --output-dir "${output}" ${layer_arguments} ${trace_arguments}
            WORKING_DIRECTORY "${SOURCE}" RESULT_VARIABLE code OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 90)
        if(NOT code EQUAL 0)
            message(FATAL_ERROR "Trace ${mode}/${suite} failed: ${stdout} ${stderr}")
        endif()
        file(READ "${output}/results.json" results)
        string(JSON count LENGTH "${results}" cases)
        math(EXPR last "${count} - 1")
        foreach(index RANGE 0 ${last})
            string(JSON status GET "${results}" cases ${index} status)
            string(JSON id GET "${results}" cases ${index} id)
            if(NOT status STREQUAL "Pass")
                message(FATAL_ERROR "Unexecuted A/B case: ${results}")
            endif()
            if(mode STREQUAL "on")
                set(sample "${output}/${profile}/${id}/0")
                file(READ "${sample}/trace.json" trace)
                string(JSON compiled GET "${trace}" compiled)
                string(JSON lost GET "${trace}" captureFailed)
                string(JSON events LENGTH "${trace}" events)
                if(NOT compiled OR lost OR events LESS 1)
                    message(FATAL_ERROR "Trace unavailable/incomplete: ${sample}")
                endif()
                file(READ "${sample}/capabilities.json" device)
                file(READ "${root}/off/${suite}/${profile}/${id}/0/capabilities.json" reference_device)
                foreach(key IN ITEMS uuid driverVersion driverInfo apiVersion validationMode)
                    string(JSON actual GET "${device}" ${key})
                    string(JSON expected GET "${reference_device}" ${key})
                    if(NOT actual STREQUAL expected)
                        message(FATAL_ERROR "Trace A/B changed device identity: ${key}")
                    endif()
                endforeach()
                file(GLOB artifacts RELATIVE "${sample}" "${sample}/*.bin" "${sample}/graph.json" "${sample}/sequence.json")
                foreach(artifact IN LISTS artifacts)
                    set(reference "${root}/off/${suite}/${profile}/${id}/0/${artifact}")
                    file(SHA256 "${sample}/${artifact}" actual_hash)
                    file(SHA256 "${reference}" expected_hash)
                    if(NOT actual_hash STREQUAL expected_hash)
                        message(FATAL_ERROR "Trace changed ${id}/${artifact}")
                    endif()
                endforeach()
            endif()
        endforeach()
    endforeach()
endforeach()
message(STATUS "Verified trace on/off readback and graph topology equivalence: ${root}")

execute_process(COMMAND "${EXECUTABLE}" --tb-run --tb-suite property --tb-validation sync
    --tb-trace --tb-trace-limit 1 --output-dir "${root}/overflow" ${layer_arguments}
    WORKING_DIRECTORY "${SOURCE}" RESULT_VARIABLE code OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 45)
file(READ "${root}/overflow/results.json" overflow)
string(JSON status GET "${overflow}" cases 0 status)
file(READ "${root}/overflow/core/RhiCommand.buffer_sequence/0/trace.json" trace)
string(JSON lost GET "${trace}" captureFailed)
if(NOT code EQUAL 1 OR NOT status STREQUAL "InfrastructureFailure" OR NOT lost)
    message(FATAL_ERROR "Truncated trace was not rejected: ${stdout} ${stderr}")
endif()
