/*
Copyright (c) 2022, NVIDIA CORPORATION. All rights reserved.

NVIDIA CORPORATION and its licensors retain all intellectual property
and proprietary rights in and to this software, related documentation
and any modifications thereto. Any use, reproduction, disclosure or
distribution of this software and related documentation without an express
license agreement from NVIDIA CORPORATION is strictly prohibited.
*/
// Metallic native descriptor handles. Generated by scripts/VendorNrd.py.
#include "REFERENCE_Copy.resources.hlsli"
#define gRectSizeInv (((REFERENCE_CopyConstants*)gNrdPush.constants)->nrd_gRectSizeInv)
#define gSplitScreen (((REFERENCE_CopyConstants*)gNrdPush.constants)->nrd_gSplitScreen)
#define gDebug (((REFERENCE_CopyConstants*)gNrdPush.constants)->nrd_gDebug)
#define gViewZScale (((REFERENCE_CopyConstants*)gNrdPush.constants)->nrd_gViewZScale)
#define gIn_Input (*DescriptorHandle<Texture2D<float4>>(uint2(gNrdPush.resources->sampled[0], 0)))
#define gOut_Output (*DescriptorHandle<RWTexture2D<float4>>(uint2(gNrdPush.resources->storage[0], 0)))
