if(NOT DEFINED RHI_EXECUTABLE OR NOT DEFINED TEST_DIRECTORY)
    message(FATAL_ERROR "RHI_EXECUTABLE and TEST_DIRECTORY are required")
endif()

# A fresh directory gives an application-binary cold run without deleting caches.
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef run_id)
set(directory "${TEST_DIRECTORY}/${run_id}")
file(MAKE_DIRECTORY "${directory}")
set(ENV{METALLIC_VK_INTERNAL_PIPELINE_CACHE} disabled)
set(ENV{METALLIC_NSIGHT_GRAPHICS_CAPTURE} 0)
set(ENV{METALLIC_NSIGHT_SHADER_DEBUG} 0)
set(ENV{METALLIC_SHADER_CAPTURE_SYMBOLS} 0)

foreach(run RANGE 1 2)
    execute_process(COMMAND "${RHI_EXECUTABLE}" --rhi-validation --gtest_color=no
        "--gtest_filter=*.shader_object_binary_process_readback" --output-dir "${directory}"
        WORKING_DIRECTORY "${directory}" RESULT_VARIABLE result
        OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 90)
    set(log "${output}\n${errors}")
    file(WRITE "${directory}/process-${run}.log" "${log}")
    if(log MATCHES "Internal pipeline cache diagnostic (requires|unsupported)")
        message(STATUS "SKIP: driver lacks internal-cache control for this test")
        return()
    endif()
    string(REGEX REPLACE "[^\n]*Vulkan validation: loader_get_json: Failed to open JSON file[^\n]*" "" checked_log "${log}")
    if(NOT result STREQUAL "0" OR checked_log MATCHES "Vulkan validation:|\\[error\\]"
        OR NOT log MATCHES "\\[  PASSED  \\] 1 test")
        message(FATAL_ERROR "ShaderObject process ${run} failed (${result}); see ${directory}/process-${run}.log")
    endif()
    if(NOT log MATCHES "Internal pipeline cache diagnostic: mode=disabled")
        message(FATAL_ERROR "Driver cache control was not active; see ${directory}/process-${run}.log")
    endif()
    set(expected_hit 0)
    if(run EQUAL 2)
        set(expected_hit 1)
    endif()
    if(NOT log MATCHES "phase=process binaryCacheHit=${expected_hit} persisted=1")
        message(FATAL_ERROR "Unexpected binary-cache path in process ${run}; see ${directory}/process-${run}.log")
    endif()
    file(SHA256 "${directory}/binary-process/process-readback.bin" pixels)
    file(COPY_FILE "${directory}/binary-process/process-observations.json" "${directory}/process-${run}.json")
    if(run EQUAL 1)
        set(cold_pixels "${pixels}")
    elseif(NOT pixels STREQUAL cold_pixels)
        message(FATAL_ERROR "Binary-created shader changed readback pixels between processes")
    endif()
endforeach()
message(STATUS "ShaderObject binary cross-process creation and pixel equality passed; evidence ${directory}")
