#pragma once
#include "Runtime/Render/Core/ComputeResourceEncoder.h"
#include "Runtime/Render/Core/NamedResourceParameters.h"
#include <cstddef>

namespace metallic::render {
// Legacy CPU binding IDs are consumed here only; no slot table is uploaded.
// Each entry writes a direct handle/span into its named CPU/Slang field.
inline constexpr ComputeResourceField kGPUProbeResourceFields[] = {
    {0, ComputeResourceBindingKind::StorageBuffer, offsetof(GPUProbeResourceParameters, input), ComputeResourceFieldFormat::Handle},
    {1, ComputeResourceBindingKind::StorageBuffer, offsetof(GPUProbeResourceParameters, output), ComputeResourceFieldFormat::Handle},
};
inline constexpr ComputeResourceLayout kGPUProbeResourceLayout{sizeof(GPUProbeResourceParameters), kGPUProbeResourceFields};

inline constexpr ComputeResourceField kSceneVisualizationResourceFields[] = {
    {0, ComputeResourceBindingKind::AccelerationStructure, offsetof(SceneResourceParameters, scene), ComputeResourceFieldFormat::Handle},
    {1, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, output), ComputeResourceFieldFormat::Handle},
    {2, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, vertices), ComputeResourceFieldFormat::Handle},
    {3, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, indices), ComputeResourceFieldFormat::Handle},
    {4, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, primitives), ComputeResourceFieldFormat::Handle},
    {5, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, instances), ComputeResourceFieldFormat::Handle},
    {6, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, materials), ComputeResourceFieldFormat::Handle},
    {7, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, materialTextures), ComputeResourceFieldFormat::IndexSpan},
    {29, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, ntcLatents), ComputeResourceFieldFormat::IndexSpan},
    {30, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, ntcConstants), ComputeResourceFieldFormat::Handle},
    {31, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, ntcWeights), ComputeResourceFieldFormat::Handle},
    {32, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, ntcInfo), ComputeResourceFieldFormat::Handle},
    {33, ComputeResourceBindingKind::Sampler, offsetof(SceneResourceParameters, ntcSampler), ComputeResourceFieldFormat::Handle},
    {54, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, positions), ComputeResourceFieldFormat::Handle},
    {55, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, celestialLights), ComputeResourceFieldFormat::Handle},
    {56, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, atmosphereParameters), ComputeResourceFieldFormat::Handle},
    {57, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, transmittance), ComputeResourceFieldFormat::Handle},
    {58, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, multiScattering), ComputeResourceFieldFormat::Handle},
    {59, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, skyView), ComputeResourceFieldFormat::Handle},
    {99, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, aerialPerspective), ComputeResourceFieldFormat::Handle},
    {101, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, cloudShadow), ComputeResourceFieldFormat::Handle},
    {90, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamPages), ComputeResourceFieldFormat::Handle},
    {91, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamPageTable), ComputeResourceFieldFormat::Handle},
    {92, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamInstances), ComputeResourceFieldFormat::Handle},
    {93, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamHeader), ComputeResourceFieldFormat::Handle},
    {94, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamPageCount), ComputeResourceFieldFormat::Handle},
    {95, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, textureFeedback), ComputeResourceFieldFormat::Handle},
    {96, ComputeResourceBindingKind::Sampler, offsetof(SceneResourceParameters, materialSampler), ComputeResourceFieldFormat::Handle},
    {97, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, materialValues), ComputeResourceFieldFormat::Handle},
};
inline constexpr ComputeResourceLayout kSceneVisualizationResourceLayout{sizeof(SceneResourceParameters), kSceneVisualizationResourceFields};

inline constexpr ComputeResourceField kOutputImageResourceFields[] = {
    {0, ComputeResourceBindingKind::StorageImage, offsetof(OutputImageResourceParameters, output), ComputeResourceFieldFormat::Handle},
};
inline constexpr ComputeResourceLayout kOutputImageResourceLayout{sizeof(OutputImageResourceParameters), kOutputImageResourceFields};

inline constexpr ComputeResourceField kTextureFeedbackResourceFields[] = {
    {0, ComputeResourceBindingKind::StorageBuffer, offsetof(TextureFeedbackResourceParameters, feedback), ComputeResourceFieldFormat::Handle},
};
inline constexpr ComputeResourceLayout kTextureFeedbackResourceLayout{sizeof(TextureFeedbackResourceParameters), kTextureFeedbackResourceFields};

inline constexpr ComputeResourceField kTextureProbeResourceFields[] = {
    {0, ComputeResourceBindingKind::SampledImage, offsetof(TextureProbeResourceParameters, textures), ComputeResourceFieldFormat::IndexSpan},
    {1, ComputeResourceBindingKind::StorageBuffer, offsetof(TextureProbeResourceParameters, output), ComputeResourceFieldFormat::Handle},
};
inline constexpr ComputeResourceLayout kTextureProbeResourceLayout{sizeof(TextureProbeResourceParameters), kTextureProbeResourceFields};

inline constexpr ComputeResourceField kPathTraceResourceFields[] = {
    {0, ComputeResourceBindingKind::AccelerationStructure, offsetof(SceneResourceParameters, scene), ComputeResourceFieldFormat::Handle},
    {1, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, output), ComputeResourceFieldFormat::Handle},
    {2, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, vertices), ComputeResourceFieldFormat::Handle},
    {3, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, indices), ComputeResourceFieldFormat::Handle},
    {4, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, primitives), ComputeResourceFieldFormat::Handle},
    {5, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, instances), ComputeResourceFieldFormat::Handle},
    {6, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, materials), ComputeResourceFieldFormat::Handle},
    {7, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, accumulationCurrent), ComputeResourceFieldFormat::Handle},
    {8, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, accumulationPrevious), ComputeResourceFieldFormat::Handle},
    {9, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, materialTextures), ComputeResourceFieldFormat::IndexSpan},
    {10, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environmentMap), ComputeResourceFieldFormat::Handle},
    {11, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, openPBRLut2D), ComputeResourceFieldFormat::IndexSpan},
    {12, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, openPBRLut3D), ComputeResourceFieldFormat::IndexSpan},
    {98, ComputeResourceBindingKind::Sampler, offsetof(SceneResourceParameters, openPBRLutSampler), ComputeResourceFieldFormat::Handle},
    {13, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environmentPdf), ComputeResourceFieldFormat::Handle},
    {20, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, cacheParams), ComputeResourceFieldFormat::Handle},
    {21, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, sharcHashEntries), ComputeResourceFieldFormat::Handle},
    {22, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, sharcAccumulation), ComputeResourceFieldFormat::Handle},
    {23, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, sharcResolved), ComputeResourceFieldFormat::Handle},
    {29, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, ntcLatents), ComputeResourceFieldFormat::IndexSpan},
    {30, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, ntcConstants), ComputeResourceFieldFormat::Handle},
    {31, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, ntcWeights), ComputeResourceFieldFormat::Handle},
    {32, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, ntcInfo), ComputeResourceFieldFormat::Handle},
    {33, ComputeResourceBindingKind::Sampler, offsetof(SceneResourceParameters, ntcSampler), ComputeResourceFieldFormat::Handle},
    {50, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lights), ComputeResourceFieldFormat::Handle},
    {51, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environmentIrradianceSH), ComputeResourceFieldFormat::Handle},
    {52, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, regirGrid), ComputeResourceFieldFormat::Handle},
    {53, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, lightsPdf), ComputeResourceFieldFormat::Handle},
    {54, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, positions), ComputeResourceFieldFormat::Handle},
    {55, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, celestialLights), ComputeResourceFieldFormat::Handle},
    {56, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, atmosphereParameters), ComputeResourceFieldFormat::Handle},
    {57, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, transmittance), ComputeResourceFieldFormat::Handle},
    {58, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, multiScattering), ComputeResourceFieldFormat::Handle},
    {59, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, skyView), ComputeResourceFieldFormat::Handle},
    {99, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, aerialPerspective), ComputeResourceFieldFormat::Handle},
    {101, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, cloudShadow), ComputeResourceFieldFormat::Handle},
    {60, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, visibility), ComputeResourceFieldFormat::Handle},
    {61, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, visibilityDepth), ComputeResourceFieldFormat::Handle},
    {62, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterVertices), ComputeResourceFieldFormat::Handle},
    {63, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterMeshlets), ComputeResourceFieldFormat::Handle},
    {64, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterRecords), ComputeResourceFieldFormat::Handle},
    {65, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterVertexIndices), ComputeResourceFieldFormat::Handle},
    {66, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterTriangles), ComputeResourceFieldFormat::Handle},
    {67, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterGeometries), ComputeResourceFieldFormat::Handle},
    {68, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterInstances), ComputeResourceFieldFormat::Handle},
    {69, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterMaterials), ComputeResourceFieldFormat::Handle},
    {70, ComputeResourceBindingKind::DataBuffer, offsetof(SceneResourceParameters, materialBins), ComputeResourceFieldFormat::DataSpan},
    {71, ComputeResourceBindingKind::DataBuffer, offsetof(SceneResourceParameters, materialTiles), ComputeResourceFieldFormat::DataSpan},
    {72, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, upscalerMotion), ComputeResourceFieldFormat::Handle},
    {73, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, upscalerDepth), ComputeResourceFieldFormat::Handle},
    {74, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, previousEnvironmentIrradianceSH), ComputeResourceFieldFormat::Handle},
    {75, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lightGridParams), ComputeResourceFieldFormat::Handle},
    {76, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lightGridLights), ComputeResourceFieldFormat::Handle},
    {77, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lightGridCandidates), ComputeResourceFieldFormat::Handle},
    {78, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lightGridCells), ComputeResourceFieldFormat::Handle},
    {79, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lightGridIndices), ComputeResourceFieldFormat::Handle},
    {80, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, view), ComputeResourceFieldFormat::Handle},
    {81, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, shadowVisibility), ComputeResourceFieldFormat::Handle},
    {82, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, shadowParameters), ComputeResourceFieldFormat::Handle},
    {83, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamRecords), ComputeResourceFieldFormat::Handle},
    {84, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamGroups), ComputeResourceFieldFormat::Handle},
    {85, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamPages), ComputeResourceFieldFormat::Handle},
    {86, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamPageTable), ComputeResourceFieldFormat::Handle},
    {87, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterFrameInfo), ComputeResourceFieldFormat::Handle},
    {88, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, rasterDomain), ComputeResourceFieldFormat::Handle},
    {90, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamPages), ComputeResourceFieldFormat::Handle},
    {91, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamPageTable), ComputeResourceFieldFormat::Handle},
    {92, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamInstances), ComputeResourceFieldFormat::Handle},
    {93, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamHeader), ComputeResourceFieldFormat::Handle},
    {94, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamPageCount), ComputeResourceFieldFormat::Handle},
    {95, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, textureFeedback), ComputeResourceFieldFormat::Handle},
    {96, ComputeResourceBindingKind::Sampler, offsetof(SceneResourceParameters, materialSampler), ComputeResourceFieldFormat::Handle},
    {97, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, materialValues), ComputeResourceFieldFormat::Handle},
};
inline constexpr ComputeResourceLayout kPathTraceResourceLayout{sizeof(SceneResourceParameters), kPathTraceResourceFields};

inline constexpr ComputeResourceField kShadowResourceFields[] = {
    {0, ComputeResourceBindingKind::AccelerationStructure, offsetof(SceneResourceParameters, scene), ComputeResourceFieldFormat::Handle},
    {1, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, output), ComputeResourceFieldFormat::Handle},
    {2, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, vertices), ComputeResourceFieldFormat::Handle},
    {3, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, indices), ComputeResourceFieldFormat::Handle},
    {4, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, primitives), ComputeResourceFieldFormat::Handle},
    {5, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, instances), ComputeResourceFieldFormat::Handle},
    {6, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, materials), ComputeResourceFieldFormat::Handle},
    {7, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, accumulationCurrent), ComputeResourceFieldFormat::Handle},
    {8, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, accumulationPrevious), ComputeResourceFieldFormat::Handle},
    {9, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, materialTextures), ComputeResourceFieldFormat::IndexSpan},
    {10, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environmentMap), ComputeResourceFieldFormat::Handle},
    {11, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, openPBRLut2D), ComputeResourceFieldFormat::IndexSpan},
    {12, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, openPBRLut3D), ComputeResourceFieldFormat::IndexSpan},
    {98, ComputeResourceBindingKind::Sampler, offsetof(SceneResourceParameters, openPBRLutSampler), ComputeResourceFieldFormat::Handle},
    {13, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environmentPdf), ComputeResourceFieldFormat::Handle},
    {20, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, cacheParams), ComputeResourceFieldFormat::Handle},
    {21, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, sharcHashEntries), ComputeResourceFieldFormat::Handle},
    {22, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, sharcAccumulation), ComputeResourceFieldFormat::Handle},
    {23, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, sharcResolved), ComputeResourceFieldFormat::Handle},
    {29, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, ntcLatents), ComputeResourceFieldFormat::IndexSpan},
    {30, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, ntcConstants), ComputeResourceFieldFormat::Handle},
    {31, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, ntcWeights), ComputeResourceFieldFormat::Handle},
    {32, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, ntcInfo), ComputeResourceFieldFormat::Handle},
    {33, ComputeResourceBindingKind::Sampler, offsetof(SceneResourceParameters, ntcSampler), ComputeResourceFieldFormat::Handle},
    {50, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lights), ComputeResourceFieldFormat::Handle},
    {51, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environmentIrradianceSH), ComputeResourceFieldFormat::Handle},
    {52, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, regirGrid), ComputeResourceFieldFormat::Handle},
    {53, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, lightsPdf), ComputeResourceFieldFormat::Handle},
    {54, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, positions), ComputeResourceFieldFormat::Handle},
    {55, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, celestialLights), ComputeResourceFieldFormat::Handle},
    {56, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, atmosphereParameters), ComputeResourceFieldFormat::Handle},
    {57, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, transmittance), ComputeResourceFieldFormat::Handle},
    {58, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, multiScattering), ComputeResourceFieldFormat::Handle},
    {59, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, skyView), ComputeResourceFieldFormat::Handle},
    {99, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, aerialPerspective), ComputeResourceFieldFormat::Handle},
    {101, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, cloudShadow), ComputeResourceFieldFormat::Handle},
    {60, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, visibility), ComputeResourceFieldFormat::Handle},
    {61, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, visibilityDepth), ComputeResourceFieldFormat::Handle},
    {62, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterVertices), ComputeResourceFieldFormat::Handle},
    {63, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterMeshlets), ComputeResourceFieldFormat::Handle},
    {64, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterRecords), ComputeResourceFieldFormat::Handle},
    {65, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterVertexIndices), ComputeResourceFieldFormat::Handle},
    {66, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterTriangles), ComputeResourceFieldFormat::Handle},
    {67, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterGeometries), ComputeResourceFieldFormat::Handle},
    {68, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterInstances), ComputeResourceFieldFormat::Handle},
    {69, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterMaterials), ComputeResourceFieldFormat::Handle},
    {70, ComputeResourceBindingKind::DataBuffer, offsetof(SceneResourceParameters, materialBins), ComputeResourceFieldFormat::DataSpan},
    {71, ComputeResourceBindingKind::DataBuffer, offsetof(SceneResourceParameters, materialTiles), ComputeResourceFieldFormat::DataSpan},
    {72, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, upscalerMotion), ComputeResourceFieldFormat::Handle},
    {73, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, upscalerDepth), ComputeResourceFieldFormat::Handle},
    {74, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, previousEnvironmentIrradianceSH), ComputeResourceFieldFormat::Handle},
    {75, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lightGridParams), ComputeResourceFieldFormat::Handle},
    {76, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lightGridLights), ComputeResourceFieldFormat::Handle},
    {77, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lightGridCandidates), ComputeResourceFieldFormat::Handle},
    {78, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lightGridCells), ComputeResourceFieldFormat::Handle},
    {79, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lightGridIndices), ComputeResourceFieldFormat::Handle},
    {80, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, shadowParameters), ComputeResourceFieldFormat::Handle},
    {81, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, shadowDepth), ComputeResourceFieldFormat::Handle},
    {82, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, shadowParameters), ComputeResourceFieldFormat::Handle},
    {82, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, penumbra), ComputeResourceFieldFormat::Handle},
    {83, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamRecords), ComputeResourceFieldFormat::Handle},
    {83, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, shadowNormal), ComputeResourceFieldFormat::Handle},
    {84, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamGroups), ComputeResourceFieldFormat::Handle},
    {84, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, shadowViewZ), ComputeResourceFieldFormat::Handle},
    {85, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamPages), ComputeResourceFieldFormat::Handle},
    {85, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, shadowMotion), ComputeResourceFieldFormat::Handle},
    {86, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamPageTable), ComputeResourceFieldFormat::Handle},
    {86, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, shadowOutput), ComputeResourceFieldFormat::Handle},
    {87, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterFrameInfo), ComputeResourceFieldFormat::Handle},
    {88, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, rasterDomain), ComputeResourceFieldFormat::Handle},
    {90, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamPages), ComputeResourceFieldFormat::Handle},
    {91, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamPageTable), ComputeResourceFieldFormat::Handle},
    {92, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamInstances), ComputeResourceFieldFormat::Handle},
    {93, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamHeader), ComputeResourceFieldFormat::Handle},
    {94, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamPageCount), ComputeResourceFieldFormat::Handle},
    {95, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, textureFeedback), ComputeResourceFieldFormat::Handle},
    {96, ComputeResourceBindingKind::Sampler, offsetof(SceneResourceParameters, materialSampler), ComputeResourceFieldFormat::Handle},
    {97, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, materialValues), ComputeResourceFieldFormat::Handle},
};
inline constexpr ComputeResourceLayout kShadowResourceLayout{sizeof(SceneResourceParameters), kShadowResourceFields};

inline constexpr ComputeResourceField kPathTraceGuidesResourceFields[] = {
    {0, ComputeResourceBindingKind::AccelerationStructure, offsetof(SceneResourceParameters, scene), ComputeResourceFieldFormat::Handle},
    {1, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, output), ComputeResourceFieldFormat::Handle},
    {2, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, vertices), ComputeResourceFieldFormat::Handle},
    {3, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, indices), ComputeResourceFieldFormat::Handle},
    {4, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, primitives), ComputeResourceFieldFormat::Handle},
    {5, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, instances), ComputeResourceFieldFormat::Handle},
    {6, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, materials), ComputeResourceFieldFormat::Handle},
    {7, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, accumulationCurrent), ComputeResourceFieldFormat::Handle},
    {8, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, accumulationPrevious), ComputeResourceFieldFormat::Handle},
    {9, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, materialTextures), ComputeResourceFieldFormat::IndexSpan},
    {10, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environmentMap), ComputeResourceFieldFormat::Handle},
    {11, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, openPBRLut2D), ComputeResourceFieldFormat::IndexSpan},
    {12, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, openPBRLut3D), ComputeResourceFieldFormat::IndexSpan},
    {98, ComputeResourceBindingKind::Sampler, offsetof(SceneResourceParameters, openPBRLutSampler), ComputeResourceFieldFormat::Handle},
    {13, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environmentPdf), ComputeResourceFieldFormat::Handle},
    {14, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, guideAlbedo), ComputeResourceFieldFormat::Handle},
    {15, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, guideSpecularAlbedo), ComputeResourceFieldFormat::Handle},
    {16, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, guideNormalRoughness), ComputeResourceFieldFormat::Handle},
    {17, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, guideMotion), ComputeResourceFieldFormat::Handle},
    {18, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, guideLinearDepth), ComputeResourceFieldFormat::Handle},
    {19, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, guideSpecularHitDistance), ComputeResourceFieldFormat::Handle},
    {20, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, cacheParams), ComputeResourceFieldFormat::Handle},
    {20, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, guideDepth), ComputeResourceFieldFormat::Handle},
    {21, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, sharcHashEntries), ComputeResourceFieldFormat::Handle},
    {22, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, sharcAccumulation), ComputeResourceFieldFormat::Handle},
    {23, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, sharcResolved), ComputeResourceFieldFormat::Handle},
    {29, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, ntcLatents), ComputeResourceFieldFormat::IndexSpan},
    {30, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, ntcConstants), ComputeResourceFieldFormat::Handle},
    {31, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, ntcWeights), ComputeResourceFieldFormat::Handle},
    {32, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, ntcInfo), ComputeResourceFieldFormat::Handle},
    {33, ComputeResourceBindingKind::Sampler, offsetof(SceneResourceParameters, ntcSampler), ComputeResourceFieldFormat::Handle},
    {50, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lights), ComputeResourceFieldFormat::Handle},
    {51, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environmentIrradianceSH), ComputeResourceFieldFormat::Handle},
    {52, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, regirGrid), ComputeResourceFieldFormat::Handle},
    {53, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, lightsPdf), ComputeResourceFieldFormat::Handle},
    {54, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, positions), ComputeResourceFieldFormat::Handle},
    {55, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, celestialLights), ComputeResourceFieldFormat::Handle},
    {56, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, atmosphereParameters), ComputeResourceFieldFormat::Handle},
    {57, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, transmittance), ComputeResourceFieldFormat::Handle},
    {58, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, multiScattering), ComputeResourceFieldFormat::Handle},
    {59, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, skyView), ComputeResourceFieldFormat::Handle},
    {99, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, aerialPerspective), ComputeResourceFieldFormat::Handle},
    {101, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, cloudShadow), ComputeResourceFieldFormat::Handle},
    {60, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, visibility), ComputeResourceFieldFormat::Handle},
    {61, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, visibilityDepth), ComputeResourceFieldFormat::Handle},
    {62, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterVertices), ComputeResourceFieldFormat::Handle},
    {63, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterMeshlets), ComputeResourceFieldFormat::Handle},
    {64, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterRecords), ComputeResourceFieldFormat::Handle},
    {65, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterVertexIndices), ComputeResourceFieldFormat::Handle},
    {66, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterTriangles), ComputeResourceFieldFormat::Handle},
    {67, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterGeometries), ComputeResourceFieldFormat::Handle},
    {68, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterInstances), ComputeResourceFieldFormat::Handle},
    {69, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterMaterials), ComputeResourceFieldFormat::Handle},
    {70, ComputeResourceBindingKind::DataBuffer, offsetof(SceneResourceParameters, materialBins), ComputeResourceFieldFormat::DataSpan},
    {71, ComputeResourceBindingKind::DataBuffer, offsetof(SceneResourceParameters, materialTiles), ComputeResourceFieldFormat::DataSpan},
    {72, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, upscalerMotion), ComputeResourceFieldFormat::Handle},
    {73, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, upscalerDepth), ComputeResourceFieldFormat::Handle},
    {74, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, previousEnvironmentIrradianceSH), ComputeResourceFieldFormat::Handle},
    {75, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lightGridParams), ComputeResourceFieldFormat::Handle},
    {76, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lightGridLights), ComputeResourceFieldFormat::Handle},
    {77, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lightGridCandidates), ComputeResourceFieldFormat::Handle},
    {78, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lightGridCells), ComputeResourceFieldFormat::Handle},
    {79, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lightGridIndices), ComputeResourceFieldFormat::Handle},
    {80, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, view), ComputeResourceFieldFormat::Handle},
    {81, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, shadowVisibility), ComputeResourceFieldFormat::Handle},
    {82, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, shadowParameters), ComputeResourceFieldFormat::Handle},
    {83, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamRecords), ComputeResourceFieldFormat::Handle},
    {84, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamGroups), ComputeResourceFieldFormat::Handle},
    {85, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamPages), ComputeResourceFieldFormat::Handle},
    {86, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamPageTable), ComputeResourceFieldFormat::Handle},
    {87, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterFrameInfo), ComputeResourceFieldFormat::Handle},
    {88, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, rasterDomain), ComputeResourceFieldFormat::Handle},
    {90, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamPages), ComputeResourceFieldFormat::Handle},
    {91, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamPageTable), ComputeResourceFieldFormat::Handle},
    {92, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamInstances), ComputeResourceFieldFormat::Handle},
    {93, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamHeader), ComputeResourceFieldFormat::Handle},
    {94, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamPageCount), ComputeResourceFieldFormat::Handle},
    {95, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, textureFeedback), ComputeResourceFieldFormat::Handle},
    {96, ComputeResourceBindingKind::Sampler, offsetof(SceneResourceParameters, materialSampler), ComputeResourceFieldFormat::Handle},
    {97, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, materialValues), ComputeResourceFieldFormat::Handle},
};
inline constexpr ComputeResourceLayout kPathTraceGuidesResourceLayout{sizeof(SceneResourceParameters), kPathTraceGuidesResourceFields};

inline constexpr ComputeResourceField kUpscalerGuideResourceFields[] = {
    {0, ComputeResourceBindingKind::SampledImage, offsetof(UpscalerGuideResourceParameters, inputMotion), ComputeResourceFieldFormat::Handle},
    {1, ComputeResourceBindingKind::SampledImage, offsetof(UpscalerGuideResourceParameters, inputDepth), ComputeResourceFieldFormat::Handle},
    {2, ComputeResourceBindingKind::StorageImage, offsetof(UpscalerGuideResourceParameters, outputMotion), ComputeResourceFieldFormat::Handle},
    {3, ComputeResourceBindingKind::StorageImage, offsetof(UpscalerGuideResourceParameters, outputDepth), ComputeResourceFieldFormat::Handle},
};
inline constexpr ComputeResourceLayout kUpscalerGuideResourceLayout{sizeof(UpscalerGuideResourceParameters), kUpscalerGuideResourceFields};

inline constexpr ComputeResourceField kRTXDIResourceFields[] = {
    {0, ComputeResourceBindingKind::AccelerationStructure, offsetof(SceneResourceParameters, scene), ComputeResourceFieldFormat::Handle},
    {1, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, output), ComputeResourceFieldFormat::Handle},
    {2, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, vertices), ComputeResourceFieldFormat::Handle},
    {3, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, indices), ComputeResourceFieldFormat::Handle},
    {4, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, primitives), ComputeResourceFieldFormat::Handle},
    {5, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, instances), ComputeResourceFieldFormat::Handle},
    {6, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, materials), ComputeResourceFieldFormat::Handle},
    {7, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, materialTextures), ComputeResourceFieldFormat::IndexSpan},
    {8, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, reservoirCurrent), ComputeResourceFieldFormat::Handle},
    {9, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, reservoirPrevious), ComputeResourceFieldFormat::Handle},
    {10, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, positionCurrent), ComputeResourceFieldFormat::Handle},
    {11, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, positionPrevious), ComputeResourceFieldFormat::Handle},
    {12, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, normalCurrent), ComputeResourceFieldFormat::Handle},
    {13, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, normalPrevious), ComputeResourceFieldFormat::Handle},
    {14, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, noisyDiffuse), ComputeResourceFieldFormat::Handle},
    {15, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, noisySpecular), ComputeResourceFieldFormat::Handle},
    {16, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, nrdNormalRoughness), ComputeResourceFieldFormat::Handle},
    {17, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, nrdMotion), ComputeResourceFieldFormat::Handle},
    {18, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, nrdViewZ), ComputeResourceFieldFormat::Handle},
    {19, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, baseColorMetalness), ComputeResourceFieldFormat::Handle},
    {20, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, emissive), ComputeResourceFieldFormat::Handle},
    {21, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environmentMap), ComputeResourceFieldFormat::Handle},
    {23, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environmentPdf), ComputeResourceFieldFormat::Handle},
    {29, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, ntcLatents), ComputeResourceFieldFormat::IndexSpan},
    {30, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, ntcConstants), ComputeResourceFieldFormat::Handle},
    {31, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, ntcWeights), ComputeResourceFieldFormat::Handle},
    {32, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, ntcInfo), ComputeResourceFieldFormat::Handle},
    {33, ComputeResourceBindingKind::Sampler, offsetof(SceneResourceParameters, ntcSampler), ComputeResourceFieldFormat::Handle},
    {50, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lights), ComputeResourceFieldFormat::Handle},
    {52, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, regirGrid), ComputeResourceFieldFormat::Handle},
    {53, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, lightsPdf), ComputeResourceFieldFormat::Handle},
    {54, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, positions), ComputeResourceFieldFormat::Handle},
    {55, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, celestialLights), ComputeResourceFieldFormat::Handle},
    {56, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, atmosphereParameters), ComputeResourceFieldFormat::Handle},
    {57, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, transmittance), ComputeResourceFieldFormat::Handle},
    {58, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, multiScattering), ComputeResourceFieldFormat::Handle},
    {59, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, skyView), ComputeResourceFieldFormat::Handle},
    {99, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, aerialPerspective), ComputeResourceFieldFormat::Handle},
    {101, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, cloudShadow), ComputeResourceFieldFormat::Handle},
    {90, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamPages), ComputeResourceFieldFormat::Handle},
    {91, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamPageTable), ComputeResourceFieldFormat::Handle},
    {92, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamInstances), ComputeResourceFieldFormat::Handle},
    {93, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamHeader), ComputeResourceFieldFormat::Handle},
    {94, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamPageCount), ComputeResourceFieldFormat::Handle},
    {95, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, textureFeedback), ComputeResourceFieldFormat::Handle},
    {96, ComputeResourceBindingKind::Sampler, offsetof(SceneResourceParameters, materialSampler), ComputeResourceFieldFormat::Handle},
    {97, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, materialValues), ComputeResourceFieldFormat::Handle},
};
inline constexpr ComputeResourceLayout kRTXDIResourceLayout{sizeof(SceneResourceParameters), kRTXDIResourceFields};

inline constexpr ComputeResourceField kSceneProbeResourceFields[] = {
    {0, ComputeResourceBindingKind::AccelerationStructure, offsetof(SceneResourceParameters, scene), ComputeResourceFieldFormat::Handle},
    {1, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, output), ComputeResourceFieldFormat::Handle},
    {2, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, vertices), ComputeResourceFieldFormat::Handle},
    {3, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, indices), ComputeResourceFieldFormat::Handle},
    {4, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, primitives), ComputeResourceFieldFormat::Handle},
    {5, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, instances), ComputeResourceFieldFormat::Handle},
    {6, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, materials), ComputeResourceFieldFormat::Handle},
    {7, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, accumulationCurrent), ComputeResourceFieldFormat::Handle},
    {8, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, accumulationPrevious), ComputeResourceFieldFormat::Handle},
    {9, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, materialTextures), ComputeResourceFieldFormat::IndexSpan},
    {10, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environmentMap), ComputeResourceFieldFormat::Handle},
    {11, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, openPBRLut2D), ComputeResourceFieldFormat::IndexSpan},
    {12, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, openPBRLut3D), ComputeResourceFieldFormat::IndexSpan},
    {98, ComputeResourceBindingKind::Sampler, offsetof(SceneResourceParameters, openPBRLutSampler), ComputeResourceFieldFormat::Handle},
    {13, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environmentPdf), ComputeResourceFieldFormat::Handle},
    {20, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, cacheParams), ComputeResourceFieldFormat::Handle},
    {21, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, sharcHashEntries), ComputeResourceFieldFormat::Handle},
    {22, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, sharcAccumulation), ComputeResourceFieldFormat::Handle},
    {23, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, sharcResolved), ComputeResourceFieldFormat::Handle},
    {29, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, ntcLatents), ComputeResourceFieldFormat::IndexSpan},
    {30, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, ntcConstants), ComputeResourceFieldFormat::Handle},
    {31, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, ntcWeights), ComputeResourceFieldFormat::Handle},
    {32, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, ntcInfo), ComputeResourceFieldFormat::Handle},
    {33, ComputeResourceBindingKind::Sampler, offsetof(SceneResourceParameters, ntcSampler), ComputeResourceFieldFormat::Handle},
    {50, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lights), ComputeResourceFieldFormat::Handle},
    {51, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environmentIrradianceSH), ComputeResourceFieldFormat::Handle},
    {52, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, regirGrid), ComputeResourceFieldFormat::Handle},
    {53, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, lightsPdf), ComputeResourceFieldFormat::Handle},
    {54, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, positions), ComputeResourceFieldFormat::Handle},
    {55, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, celestialLights), ComputeResourceFieldFormat::Handle},
    {56, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, atmosphereParameters), ComputeResourceFieldFormat::Handle},
    {57, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, transmittance), ComputeResourceFieldFormat::Handle},
    {58, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, multiScattering), ComputeResourceFieldFormat::Handle},
    {59, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, skyView), ComputeResourceFieldFormat::Handle},
    {99, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, aerialPerspective), ComputeResourceFieldFormat::Handle},
    {101, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, environment) + offsetof(EnvironmentResourceParameters, cloudShadow), ComputeResourceFieldFormat::Handle},
    {60, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, visibility), ComputeResourceFieldFormat::Handle},
    {61, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, visibilityDepth), ComputeResourceFieldFormat::Handle},
    {62, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterVertices), ComputeResourceFieldFormat::Handle},
    {63, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, probeOutput), ComputeResourceFieldFormat::Handle},
    {64, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterRecords), ComputeResourceFieldFormat::Handle},
    {65, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterVertexIndices), ComputeResourceFieldFormat::Handle},
    {66, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterTriangles), ComputeResourceFieldFormat::Handle},
    {67, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterGeometries), ComputeResourceFieldFormat::Handle},
    {68, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterInstances), ComputeResourceFieldFormat::Handle},
    {69, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterMaterials), ComputeResourceFieldFormat::Handle},
    {70, ComputeResourceBindingKind::DataBuffer, offsetof(SceneResourceParameters, materialBins), ComputeResourceFieldFormat::DataSpan},
    {71, ComputeResourceBindingKind::DataBuffer, offsetof(SceneResourceParameters, materialTiles), ComputeResourceFieldFormat::DataSpan},
    {72, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, upscalerMotion), ComputeResourceFieldFormat::Handle},
    {73, ComputeResourceBindingKind::StorageImage, offsetof(SceneResourceParameters, upscalerDepth), ComputeResourceFieldFormat::Handle},
    {74, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, previousEnvironmentIrradianceSH), ComputeResourceFieldFormat::Handle},
    {75, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lightGridParams), ComputeResourceFieldFormat::Handle},
    {76, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lightGridLights), ComputeResourceFieldFormat::Handle},
    {77, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lightGridCandidates), ComputeResourceFieldFormat::Handle},
    {78, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lightGridCells), ComputeResourceFieldFormat::Handle},
    {79, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, lightGridIndices), ComputeResourceFieldFormat::Handle},
    {80, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, view), ComputeResourceFieldFormat::Handle},
    {81, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, shadowVisibility), ComputeResourceFieldFormat::Handle},
    {82, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, shadowParameters), ComputeResourceFieldFormat::Handle},
    {83, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamRecords), ComputeResourceFieldFormat::Handle},
    {84, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamGroups), ComputeResourceFieldFormat::Handle},
    {85, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamPages), ComputeResourceFieldFormat::Handle},
    {86, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamPageTable), ComputeResourceFieldFormat::Handle},
    {87, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rasterFrameInfo), ComputeResourceFieldFormat::Handle},
    {88, ComputeResourceBindingKind::SampledImage, offsetof(SceneResourceParameters, rasterDomain), ComputeResourceFieldFormat::Handle},
    {90, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamPages), ComputeResourceFieldFormat::Handle},
    {91, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamPageTable), ComputeResourceFieldFormat::Handle},
    {92, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamInstances), ComputeResourceFieldFormat::Handle},
    {93, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, rayStreamHeader), ComputeResourceFieldFormat::Handle},
    {94, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, streamPageCount), ComputeResourceFieldFormat::Handle},
    {95, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, textureFeedback), ComputeResourceFieldFormat::Handle},
    {96, ComputeResourceBindingKind::Sampler, offsetof(SceneResourceParameters, materialSampler), ComputeResourceFieldFormat::Handle},
    {97, ComputeResourceBindingKind::StorageBuffer, offsetof(SceneResourceParameters, materialValues), ComputeResourceFieldFormat::Handle},
};
inline constexpr ComputeResourceLayout kSceneProbeResourceLayout{sizeof(SceneResourceParameters), kSceneProbeResourceFields};

inline constexpr ComputeResourceField kVisibilityMaterialResourceFields[] = {
    {0, ComputeResourceBindingKind::StorageImage, offsetof(VisibilityMaterialResourceParameters, output), ComputeResourceFieldFormat::Handle},
    {1, ComputeResourceBindingKind::SampledImage, offsetof(VisibilityMaterialResourceParameters, visibility), ComputeResourceFieldFormat::Handle},
    {2, ComputeResourceBindingKind::StorageBuffer, offsetof(VisibilityMaterialResourceParameters, instances), ComputeResourceFieldFormat::Handle},
    {3, ComputeResourceBindingKind::StorageBuffer, offsetof(VisibilityMaterialResourceParameters, materials), ComputeResourceFieldFormat::Handle},
    {4, ComputeResourceBindingKind::StorageBuffer, offsetof(VisibilityMaterialResourceParameters, records), ComputeResourceFieldFormat::Handle},
    {5, ComputeResourceBindingKind::StorageBuffer, offsetof(VisibilityMaterialResourceParameters, meshlets), ComputeResourceFieldFormat::Handle},
    {6, ComputeResourceBindingKind::StorageBuffer, offsetof(VisibilityMaterialResourceParameters, vertices), ComputeResourceFieldFormat::Handle},
    {7, ComputeResourceBindingKind::StorageBuffer, offsetof(VisibilityMaterialResourceParameters, vertexIndices), ComputeResourceFieldFormat::Handle},
    {8, ComputeResourceBindingKind::StorageBuffer, offsetof(VisibilityMaterialResourceParameters, triangles), ComputeResourceFieldFormat::Handle},
    {9, ComputeResourceBindingKind::StorageBuffer, offsetof(VisibilityMaterialResourceParameters, geometries), ComputeResourceFieldFormat::Handle},
    {10, ComputeResourceBindingKind::StorageBuffer, offsetof(VisibilityMaterialResourceParameters, streamRecords), ComputeResourceFieldFormat::Handle},
    {11, ComputeResourceBindingKind::StorageBuffer, offsetof(VisibilityMaterialResourceParameters, groups), ComputeResourceFieldFormat::Handle},
    {12, ComputeResourceBindingKind::StorageBuffer, offsetof(VisibilityMaterialResourceParameters, pages), ComputeResourceFieldFormat::Handle},
    {13, ComputeResourceBindingKind::StorageBuffer, offsetof(VisibilityMaterialResourceParameters, pageTable), ComputeResourceFieldFormat::Handle},
    {14, ComputeResourceBindingKind::StorageBuffer, offsetof(VisibilityMaterialResourceParameters, pageCount), ComputeResourceFieldFormat::Handle},
};
inline constexpr ComputeResourceLayout kVisibilityMaterialResourceLayout{sizeof(VisibilityMaterialResourceParameters), kVisibilityMaterialResourceFields};

} // namespace metallic::render
