"""Refresh Metallic's NRD shader snapshot (no SDK or shader build at configure time).

Run from the repository root with Python 3. The CPU schedules are maintained
separately under Source/Runtime/Render/Denoising and must be reviewed on upgrades.
"""
from pathlib import Path
import re
import shutil
import subprocess

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'External/nrd/Shaders'
DEST = ROOT / 'Shaders/Libraries/Denoising/NRD'
REVISION = '36183520b006b65860bebc96d3dd7185e5edeb45'
revision = subprocess.check_output(['git', '-C', str(SOURCE.parent), 'rev-parse', 'HEAD'], text=True).strip()
if revision != REVISION:
    raise SystemExit('Review the NRD CPU recipes and update REVISION before importing a new NRD version.')
DEST.mkdir(parents=True, exist_ok=True)

for source in (SOURCE / 'Include').glob('*.hlsli'):
    if not source.name.startswith('SIGMA'):
        shutil.copy2(source, DEST / source.name)
        content = (DEST / source.name).read_text().replace(
            'pos.x < 0.0 || pos.x > gRectSizeMinusOne.x',
            '(pos.x < 0.0) || (pos.x > gRectSizeMinusOne.x)')
        (DEST / source.name).write_text(content)
header = (DEST / 'NRD.hlsli').read_text()
start = header.index('// ( Optional ) Bindings')
end = header.index('// ( Optional ) Entry point', start)
header = header[:start] + header[end:]
start = header.index('#define NRD_MERGE_TOKENS_')
end = header.index('// GLSL', start)
end = header.rfind('//======', start, end)
header = header[:start] + '// Resource access is supplied exclusively by Metallic Bindless.hlsli.\n#define NRD_EXPORT\n\n' + header[end:]
(DEST / 'NRD.hlsli').write_text(header)
shutil.copy2(ROOT / 'External/nrd/LICENSE.txt', DEST / 'LICENSE.txt')

for source in SOURCE.glob('*.resources.hlsli'):
    if source.name.startswith(('REBLUR_', 'RELAX_', 'REFERENCE_')):
        # Retain logical input slots for the CPU field lists; remove HLSL registers.
        declarations = re.sub(r',\s*[tus]\s*,\s*(\d+)\s*\)', r', \1 )', source.read_text())
        (DEST / source.name).write_text(declarations)

for source in SOURCE.glob('*.cs.hlsl'):
    if not source.name.startswith(('REBLUR_', 'RELAX_', 'REFERENCE_')):
        continue
    name = source.name.removesuffix('.cs.hlsl')
    resource = (SOURCE / (name + '.resources.hlsli')).read_text()
    constants = re.findall(r'NRD_CONSTANT\(\s*\w+\s*,\s*(\w+)\s*\)', resource)
    for family in ('REBLUR', 'RELAX'):
        if family + '_SHARED_CONSTANTS' in resource:
            constants += re.findall(r'NRD_CONSTANT\(\s*\w+\s*,\s*(\w+)\s*\)',
                                   (DEST / (family + '_Config.hlsli')).read_text())
    binding = resource[:resource.index('*/') + 2] + '\n'
    binding += '// Metallic native descriptor handles. Generated by scripts/VendorNrd.py.\n'
    binding += '#include "' + name + '.resources.hlsli"\n'
    for field in dict.fromkeys(constants):
        binding += f'#define {field} ((({name}Constants*)gNrdPush.constants)->nrd_{field})\n'
    # Preserve permutation guards, replacing declarations with descriptor lookups.
    for line in resource.splitlines():
        match = re.search(r'NRD_(INPUT|OUTPUT)\(\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*,\s*\w+\s*,\s*(\d+)\s*\)', line)
        sampler = re.search(r'NRD_SAMPLER\(\s*(\w+)\s*,\s*(\w+)\s*,\s*\w+\s*,\s*(\d+)\s*\)', line)
        if match:
            access, texture, dtype, field, slot = match.groups()
            table = 'sampled' if access == 'INPUT' else 'storage'
            binding += f'#define {field} (*DescriptorHandle<{texture}<{dtype}>>(uint2(gNrdPush.resources->{table}[{slot}], 0)))\n'
        elif sampler:
            dtype, field, slot = sampler.groups()
            binding += f'#define {field} (*DescriptorHandle<{dtype}>(uint2(gNrdPush.resources->samplers[{slot}], 0)))\n'
        elif re.match(r'\s*#\s*(if|elif|else|endif)\b', line):
            binding += line + '\n'
    (DEST / (name + '.bindings.hlsli')).write_text(binding)
    shader = '#include "Bindless.hlsli"\n' + source.read_text()
    shader = shader.replace(name + '.resources.hlsli', name + '.bindings.hlsli')
    shader = shader.replace('NRD_EXPORT void NRD_CS_MAIN', '[shader("compute")] NRD_EXPORT void NRD_CS_MAIN')
    if name.startswith('REFERENCE_'):
        output = 'gInOut_History' if 'TemporalAccumulation' in name else 'gOut_Output'
        shader = shader.replace('    NRD_CTA_ORDER_DEFAULT;', '    NRD_CTA_ORDER_DEFAULT;\n'
            '    uint width, height;\n'
            f'    {output}.GetDimensions(width, height);\n'
            '    if (any(pixelPos >= uint2(width, height))) return;')
    (DEST / (name + '.slang')).write_text(shader)

print('Updated NRD REBLUR, RELAX, and REFERENCE shader sources in', DEST)
