if(NOT DEFINED LOOKDEV_EXECUTABLE OR NOT DEFINED TEST_DIRECTORY OR NOT DEFINED SOURCE_DIRECTORY)
    message(FATAL_ERROR "LOOKDEV_EXECUTABLE, TEST_DIRECTORY and SOURCE_DIRECTORY are required")
endif()

file(MAKE_DIRECTORY "${TEST_DIRECTORY}")
set(ENV{METALLIC_NSIGHT_GRAPHICS_CAPTURE} 0)
set(ENV{METALLIC_NSIGHT_SHADER_DEBUG} 0)
set(ENV{METALLIC_SHADER_CAPTURE_SYMBOLS} 0)
set(ENV{METALLIC_SMOKE_TEST_HIDDEN} 1)
set(ENV{METALLIC_SMOKE_TEST_FRAMES} 8)
set(ENV{METALLIC_DEBUG_VALIDATION} 1)
# Cache reuse must work across processes without relying on the driver's cache.
set(ENV{METALLIC_VK_INTERNAL_PIPELINE_CACHE} disabled)
foreach(option IN ITEMS METALLIC_SMOKE_TEST_PAINTER_SWITCH METALLIC_SMOKE_TEST_STUDIO_SWITCH
        METALLIC_SMOKE_TEST_VBUFFER_PREVIEW METALLIC_VK_PIPELINE_STATISTICS)
    unset(ENV{${option}})
endforeach()

set(samples openpbr-lookdev pathtracing-sharc-meet-mat)
foreach(sample IN LISTS samples)
    set(cache_name ScenePathTracePass)
    set(minimum_hits 1)
    if(sample STREQUAL "pathtracing-sharc-meet-mat")
        set(minimum_hits 5)
    endif()
    foreach(run RANGE 1 2)
        execute_process(
            COMMAND "${LOOKDEV_EXECUTABLE}" --sample "${sample}" --skip-shader-warmup --smoke-test
            WORKING_DIRECTORY "${TEST_DIRECTORY}"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 180)
        set(log "${output}\n${errors}")
        file(WRITE "${TEST_DIRECTORY}/${sample}-${run}.log" "${log}")
        if(log MATCHES "Internal pipeline cache diagnostic (requires|unsupported)")
            message(STATUS "SKIP: driver lacks the internal-cache control needed for this test")
            return()
        endif()
        # Keep the raw loader diagnostic in the log, but exclude this known
        # missing-layer-manifest message from GPU validation checks.
        string(REGEX REPLACE "[^\n]*Vulkan validation: loader_get_json: Failed to open JSON file[^\n]*" "" checked_log "${log}")
        if(NOT result STREQUAL "0" OR checked_log MATCHES "Vulkan validation:|\\[error\\]"
                OR NOT log MATCHES "\\[Smoke\\] Presented editor frame")
            message(FATAL_ERROR "${sample} run ${run} failed (${result}); see ${TEST_DIRECTORY}/${sample}-${run}.log")
        endif()
        if(run EQUAL 2)
            string(REGEX MATCHALL "\\[ShaderRegistry\\] PSO cache group=${cache_name} hits=[0-9]+ misses=[0-9]+" entries "${log}")
            set(covered FALSE)
            foreach(entry IN LISTS entries)
                if(NOT entry MATCHES "hits=([0-9]+) misses=0$")
                    message(FATAL_ERROR "${sample} recreated a PSO in its second process: ${entry}")
                endif()
                if(CMAKE_MATCH_1 GREATER_EQUAL minimum_hits)
                    set(covered TRUE)
                endif()
            endforeach()
            if(NOT covered)
                message(FATAL_ERROR "${sample} did not reuse all ${minimum_hits} expected PSOs; see ${TEST_DIRECTORY}/${sample}-${run}.log")
            endif()
            string(REGEX MATCHALL "\\[ShaderRegistry\\] PSO cache group=ShaderRegistry-EditorDisplay-[a-z0-9]+ hits=[0-9]+ misses=[0-9]+" display_entries "${log}")
            set(display_covered FALSE)
            foreach(entry IN LISTS display_entries)
                if(NOT entry MATCHES "hits=([0-9]+) misses=0$")
                    message(FATAL_ERROR "${sample} recreated an editor display PSO in its second process: ${entry}")
                endif()
                if(CMAKE_MATCH_1 GREATER_EQUAL 2)
                    set(display_covered TRUE)
                endif()
            endforeach()
            if(NOT display_covered)
                message(FATAL_ERROR "${sample} did not reuse editor display PSOs; see ${TEST_DIRECTORY}/${sample}-${run}.log")
            endif()
            if(NOT EXISTS "${SOURCE_DIRECTORY}/.cache/pso/${cache_name}.pso")
                message(FATAL_ERROR "${cache_name} did not persist its cache")
            endif()
        endif()
    endforeach()
    message(STATUS "${sample}: persistent PSOs reused across processes")
endforeach()
