# Run with cmake -DSOURCE_DIRECTORY=<repo> -P Tools/CheckWorkingColor.cmake.
if(NOT DEFINED SOURCE_DIRECTORY)
    get_filename_component(SOURCE_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
file(GLOB_RECURSE shaders "${SOURCE_DIRECTORY}/Shaders/Features/*.slang" "${SOURCE_DIRECTORY}/Shaders/Modules/*.slang")
foreach(shader IN LISTS shaders)
    if(shader MATCHES "/Core/WorkingColor\\.slang$")
        continue()
    endif()
    file(READ "${shader}" source)
    if(source MATCHES "0\\.2126|0\\.7152|0\\.0722|sRGB_2_AP1")
        message(FATAL_ERROR "Scene-color assumption outside WorkingColor: ${shader}")
    endif()
endforeach()
message(STATUS "WorkingColor scene luminance audit passed")
