# Include after project(), before creating any targets, in both builds.
option(METALLIC_USE_SCCACHE "Cache C/C++ compilation with sccache" OFF)
if(METALLIC_USE_SCCACHE)
    if(NOT CMAKE_GENERATOR MATCHES "Ninja|Makefiles")
        message(FATAL_ERROR "METALLIC_USE_SCCACHE requires Ninja or Makefiles")
    endif()
    find_program(METALLIC_SCCACHE_EXECUTABLE NAMES sccache REQUIRED)
    if(MSVC)
        if(NOT POLICY CMP0141)
            message(FATAL_ERROR "MSVC sccache support requires CMake 3.25 or newer")
        endif()
        set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "$<$<CONFIG:Debug,RelWithDebInfo>:Embedded>")
    endif()
endif()

foreach(language IN ITEMS C CXX)
    set(launcher "${CMAKE_${language}_COMPILER_LAUNCHER}")
    # Do not wrap our own launcher again during reconfiguration.
    if(launcher MATCHES "RunMsvcCompiler.cmake")
        set(launcher "")
    endif()
    if(METALLIC_USE_SCCACHE)
        if(launcher AND NOT launcher STREQUAL METALLIC_SCCACHE_EXECUTABLE)
            message(FATAL_ERROR "Choose either METALLIC_USE_SCCACHE or CMAKE_${language}_COMPILER_LAUNCHER")
        endif()
        set(launcher "${METALLIC_SCCACHE_EXECUTABLE}")
    endif()
    if(MSVC AND CMAKE_GENERATOR MATCHES "Ninja")
        # The wrapper accepts a complete command: optional cache, compiler, args.
        list(PREPEND launcher "${CMAKE_COMMAND}" -P "${CMAKE_CURRENT_LIST_DIR}/RunMsvcCompiler.cmake" --)
        set(CMAKE_${language}_CL_SHOWINCLUDES_PREFIX "Note: including file:  ")
        set(CMAKE_CL_SHOWINCLUDES_PREFIX "Note: including file:  ")
    endif()
    set(CMAKE_${language}_COMPILER_LAUNCHER "${launcher}")
endforeach()
unset(launcher)
unset(language)
