option(METALLIC_ENABLE_DLSS_NR "Enable experimental direct NGX DLSS Neural Rendering (Windows/Vulkan)" OFF)
if(METALLIC_STREAMLINE_SDK_ROOT)
    set(METALLIC_DLSS_NR_DEFAULT_NGX_ROOT "${METALLIC_STREAMLINE_SDK_ROOT}/external/ngx-sdk")
else()
    set(METALLIC_DLSS_NR_DEFAULT_NGX_ROOT "${CMAKE_SOURCE_DIR}/External/streamline/external/ngx-sdk")
endif()
set(METALLIC_DLSS_NR_NGX_ROOT "${METALLIC_DLSS_NR_DEFAULT_NGX_ROOT}" CACHE PATH "NGX SDK used by experimental DLSS-NR")
set(METALLIC_DLSS_NR_RUNTIME "${CMAKE_SOURCE_DIR}/External/DLSSNR/nvngx_dlssnr.dll" CACHE FILEPATH "User-provided DLSS-NR runtime to deploy")

add_library(metallic_dlss_nr INTERFACE)
add_library(metallic::dlss_nr ALIAS metallic_dlss_nr)
set(METALLIC_HAS_DLSS_NR 0)
if(METALLIC_ENABLE_DLSS_NR)
    if(NOT WIN32 OR NOT MSVC OR NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
        message(FATAL_ERROR "Experimental DLSS-NR currently requires Windows x64/MSVC.")
    endif()
    if(NOT METALLIC_HAS_STREAMLINE)
        message(FATAL_ERROR "Experimental DLSS-NR requires Streamline for NGX core initialization and Vulkan extensions.")
    endif()
    foreach(required_file include/nvsdk_ngx_vk.h include/nvsdk_ngx_params.h)
        if(NOT EXISTS "${METALLIC_DLSS_NR_NGX_ROOT}/${required_file}")
            message(FATAL_ERROR "Missing NGX SDK file: ${METALLIC_DLSS_NR_NGX_ROOT}/${required_file}")
        endif()
        file(READ "${METALLIC_DLSS_NR_NGX_ROOT}/${required_file}" file_prefix LIMIT 128)
        if(file_prefix MATCHES "version https://git-lfs.github.com/spec/v1")
            message(FATAL_ERROR "NGX SDK file is an LFS pointer: ${required_file}. Use the packaged Streamline SDK or fetch its LFS files.")
        endif()
    endforeach()
    if(NOT EXISTS "${METALLIC_DLSS_NR_RUNTIME}")
        message(FATAL_ERROR "Set METALLIC_DLSS_NR_RUNTIME to your nvngx_dlssnr.dll. Metallic does not download or redistribute it.")
    endif()
    set(METALLIC_HAS_DLSS_NR 1)
    target_include_directories(metallic_dlss_nr INTERFACE "${METALLIC_DLSS_NR_NGX_ROOT}/include")
    message(STATUS "Experimental DLSS-NR enabled: ${METALLIC_DLSS_NR_RUNTIME}")
endif()
target_compile_definitions(metallic_dlss_nr INTERFACE METALLIC_HAS_DLSS_NR=${METALLIC_HAS_DLSS_NR})

function(metallic_copy_dlss_nr_runtime target_name)
    if(METALLIC_HAS_DLSS_NR)
        add_custom_command(TARGET ${target_name} POST_BUILD
            COMMAND ${CMAKE_COMMAND} -E copy_if_different
                "${METALLIC_DLSS_NR_RUNTIME}" "$<TARGET_FILE_DIR:${target_name}>/nvngx_dlssnr.dll"
            VERBATIM)
    endif()
endfunction()
